kumuluzee:
  name: mag2020-media-metadata
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8007
    http:
      port: 8007
  datasources:
    - jndi-name: jdbc/ProjectDB
      connection-url: jdbc:mysql://mag2020.cd0nfxw2grsa.eu-central-1.rds.amazonaws.com:3306/Project
      username: admin_uros
      password: admin_uros123
      max-pool-size: 20
  grpc:
    server:
      url: localhost
      http:
        port: 9005
    clients:
      - name: awsStorageClient
        port: 9001
        address: localhost