kumuluzee:
  name: mag2020-media-metadata
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8007
    http:
      port: 8007
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"
  datasources:
    - jndi-name: jdbc/ProjectDB
      connection-url: jdbc:mysql://mag2020.cd0nfxw2grsa.eu-central-1.rds.amazonaws.com:3306/Project
      username: admin_uros
      password: admin_uros123
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ProjectDB
  opentracing:
    jaeger:
      service-name: mag2020-media-metadata # if not set kumuluzee.name value is used
      agent-host: localhost # default agent host
      agent-port: 5775 # default agent port
      reporter:
        log-spans: true
        max-queue-size: 10000
        flush-interval: 1000
      sampler:
        type: const # default sampler type
        param: 1 # default sampler param
        manager-host-port: http://localhost:5775
      traceid-128bit: true
  grpc:
    server:
      url: localhost
      http:
        port: 9005
    clients:
      - name: awsStorageClient
        port: 9001
        address: localhost
mp:
  opentracing:
    server:
      operation-name-provider: http-path
      skip-pattern: /openapi.*|/health.*